SELECT * FROM db_empl.t_offices;

INSERT INTO T_OFFICES
(
  OFFC_ID, OFFC_COUNTRY, OFFC_CITY, OFFC_DESCRIPTION
)
VALUES
(
  10, 'España', 'Madrid', 'Oficina central'
);

INSERT INTO T_OFFICES
(
  OFFC_ID, OFFC_COUNTRY, OFFC_CITY, OFFC_DESCRIPTION
)
VALUES
(
  20, 'Chile', 'Santiago', 'Oficina principal de Chile'
),
(
  30, 'Argentina', 'Buenos aires', NULL
);

ALTER TABLE T_OFFICES ADD PRIMARY KEY (OFFC_ID);

CREATE TABLE `T_EMPLOYEES` (
  `EMPL_ID` INT NOT NULL AUTO_INCREMENT,
  `OFFC_ID` INT NOT NULL,
  `KNLN_ID` INT,
  `EMPL_FORNAME` VARCHAR(50) NOT NULL,
  `EMPL_MIDDLE_NAME` VARCHAR(50),
  `EMPL_SURNAME` VARCHAR(50) NOT NULL,
  `EMPL_NUMBER` INT NOT NULL,
  `EMPL_HIRE_DATE` DATETIME NOT NULL,
  `EMPL_MENTOR_ID` INT,
  PRIMARY KEY (`EMPL_ID`));
